### ISSUE TITLE
Haut.

### ISSUE THREAD

**Issue by benniii1337** [phob/pillarsofeternity-german-patch#114]
Falls jemand eine Aufgabe sucht, ich hätte da eine zu vergeben. Suchet nach dem Wort "Haut" innerhalb der `items.stringtable` und ihr werdet feststellen das es den Übersetzern wohl sehr am Herzen lag.

Mir geht es da im wesentlichen um `Antilopenhaut`, `Bärenhaut`, `Keilerhaut`, `Löwenhaut`, `Hirschhaut`, `Wolfshaut`, `Geisterwandler-(Bären)Haut` und `Stelgaerhaut`

Die sollten doch bitte an Fell angepasst werden, ebenso die Beschreibungstexte.

Allerdings trifft man auch auf 2 Gegenstände bei denen das nicht so leicht ist:
- `Sieben Skuldr-Haut` (engl.: Seven Skuldr's-Worth)
- `Haut des großen westlichen Hirsches` (engl.: Husk of the Great Western Stag)

'Husk' würde sich in 'Hülle' übersetzen lassen, aber bei 'Worth' klingt in Verbindung mit 'Sieben Skuldr' gar nichts stimmig. Wenn der Plural von Skuldr Skuldre wäre könnte man wenigstens sinngemäß 'Sieben Skuldre-Wert' nehmen.

Die `Rohhautrüstung` müsste dann sinngemäß eigentlich auch eher eine `Fellrüstung` sein.
Und `Textilrüstung` (engl.: Cloth Armor) klingt auch falsch, oder ist das nur meine geschädigte WoW-Vergangenheit die da gerne `Stoffrüstung` sehen möchte?

**Comment by MadOwlkin** [comment]
Ich hätte jetzt Cloth mit "Tuch" oder sowas übersetzt (und habe damit laut Google einen DSA-Infekt ;) )

Bisschen Google findet dann später den Gambeson, eine Stoffrüstung, die dann durch die Brigantine ersetzt wurde (und die ist immerhin im Spiel)... aber allgemein driftet das etwas zu weit ab.

**Comment by GrafWasili** [comment]
finde ich sehr gut, vielleicht kann man das noch bisschen diversifizieren z.B. Löwenpelz und Wolfspelz.

Bei der Gelegenheit würde ich auch die Bindestrich-Konstruktionen ersetzen: Fell eines Geisterwandlerbären.

Ich würde die Aufgabe auch annehmen, aber heut nicht mehr...

**Comment by GrafWasili** [comment]
Ich hab die Hautkorrekturen gemacht, aber solange der Pull request zu Pallid Knight noch offen ist, kann ich die schlecht als einzelnen pull request stellen, weil masterzweig und so...

**Comment by MadOwlkin** [comment]
Dein letztes Pullrequest ist gemergt. Danke, dass du nicht einfach weiter auf master draufgestapelt hast ;)

Allgemein ist bei sowas das arbeiten von einem Branch aus recht praktisch. Den kann man dann fern von Änderungen eines anderen branches halten und nur noch die für das Pullrequest notwendigen Änderungen daran durchführen.

**Comment by GrafWasili** [comment]
Alles klar, werd bei Gelegenheit mal das Branchen probieren (für die Häute ist es jetzt schon wieder zu spät ^^)

**Comment by benniii1337** [comment]
done @ #122
