### ISSUE TITLE
Patch 1.05

### ISSUE THREAD

**Issue by AurelioSilver** [phob/pillarsofeternity-german-patch#131]
Beta Patch 1.05 kommt bald raus. Da einige Balance Änderungen drinnen sind, sind vermutlich auch Textänderungen dabei.

**Comment by AurelioSilver** [comment]
Es sind einige Änderungen in Patch 1.05 vorhanden. Die werde ich bei Gelegenheit durchgehen.

**Comment by AurelioSilver** [comment]
DE Dateien, die sich geändert haben:
characters.stringtable
cyclopedia.stringtable
gui.stringtable
itemmods.stringtable
items.stringtable
maps.stringtable

**Comment by AurelioSilver** [comment]
EN Dateien, die sich geändert haben:
conversations\companions\companion_cv_eder_quest.stringtable

game\abilities.stringtable
game\characters.stringtable
game\cyclopedia.stringtable
game\gui.stringtable
game\itemmods.stringtable
game\items.stringtable
game\maps.stringtable
quests\07_gilded_vale\07_tsk_late_for_dinner.stringtable

---

Nur für EN relevante Änderungen:
conversations\03_defiance_bay_ondra_gift\03_cv_marceno.stringtable
conversations\00_dyrwood\00_cv_eder_looters.stringtable
conversations\01_defiance_bay_copperlane\01_cv_gordy.stringtable
conversations\01_defiance_bay_copperlane\01_cv_helig.stringtable
conversations\06_stronghold\06_cv_steward.stringtable
conversations\07_gilded_vale\07_si_temple_bells.stringtable
conversations\08_wilderness\08_si_sky_dragon_ridge.stringtable
conversations\10_od_nua\1003_cv_thulgar.stringtable
conversations\10_od_nua\1012_cv_vithrack_leader.stringtable
conversations\10_od_nua\1014_cv_od_nua.stringtable
conversations\10_od_nua\1015_cv_adra_dragon.stringtable
conversations\11_hearthsong\11_cv_llensi.stringtable
conversations\13_twin_elms_elms_reach\13_cv_hylea.stringtable
conversations\13_twin_elms_elms_reach\13_cv_rymrgand_coalition.stringtable
conversations\13_twin_elms_elms_reach\13_cv_sidha.stringtable
conversations\13_twin_elms_elms_reach\13_cv_simoc.stringtable
conversations\14_burial_isle\14_cv_thaos.stringtable
conversations\companions\companion_cv_durance_hub_ashfall_v2.stringtable
conversations\companions\companion_cv_durance_v2.stringtable
conversations\companions\companion_cv_gm_02.stringtable
game\recipes.stringtable

**Comment by AurelioSilver** [comment]
Ich kann bei Interesse die 1.05 englischen und deutschen Dateien zuschicken. Bitte PM im Obsidian Forum schicken.

**Comment by AurelioSilver** [comment]
Ok, relevaten Dateien ausortiert. Die anderen Änderunen waren nur Rechtschreibfehler in der englischen Version.

Wie machen wir das nun mit den neuen Änderungen? Ich kann erstmal die neuen Texte als englischen Text hinzufügen. In den übrigen Dateien sind teilweise nur Rechtschreibfehler koorigiert worden, aber es sind auch neue Texte hinzugekommen oder wurden abgeändert.

**Comment by Xaratas** [comment]
Auf nen neuen Branch mit den geänderten und neuen Texten und die dann Stückweise durchgehen. Wenn alles Deutsch ist zurück mergen.

**Comment by AurelioSilver** [comment]
Hab soweit alles was sich geändert hat und 1.04 nicht beeinflusst geändert. Der Rest sind nun neue Texte oder Änderungen. Da versuche ich es mal mit einem Branch... Eventuell kann Pho eine neue Version für 1.04 nach dem letzten Pull Request bauen?

**Comment by AurelioSilver** [comment]
Patch 1.05 scheint nun da zu sein. GOG Version müßte dann bald folgen.

**Comment by nkemnitz** [comment]
Gog ist auch da - hast du schon mit den 1.05 Änderungen weitergemacht (abgesehen von denen in #140)? Wenn nicht, kann ich das heut abend zusammenbasteln. Will nur nicht, dass wir uns doppelte Arbeit machen.

**Comment by AurelioSilver** [comment]
Nein, nicht wirklich. Wollte erst die neuen Sachen im Master haben und dann switchen. Hatte nur erstmal alles was so von 1.05 in 1.04 passte übertragen. Änderungen und neue Texte wollte ich dann später hinzufügen. Heute werde ich nicht da zukommen.

**Comment by nkemnitz** [comment]
Dann schnapp' ich dir das weg - brauch noch ne Beschäftigung für heute :P
