### ISSUE TITLE
Zwei kleine Fehler

### ISSUE THREAD

**Issue by tremd** [phob/pillarsofeternity-german-patch#145]
http://i.imgur.com/fnwQOle.jpg
http://i.imgur.com/6GSANa0.jpg

**Comment by AurelioSilver** [comment]
Danke. Koorigiert.

**Comment by tremd** [comment]
Kann ich das nun schließen oder muss das erst jemand übernehmen?
Wird es dadurch das jemand ein Fix liefert direkt in die neuste Version später eingebaut?

**Comment by Xaratas** [comment]
Die Korrektur ist jetzt im Git drin, im nächsten Release/ zu Nexus hochgeladenem Paket ist es für alle drin.

**Comment by tremd** [comment]
Danke Xaratas - Problem gelöst. Ich schließe.
