### ISSUE TITLE
Ausländer / Fremder

### ISSUE THREAD

**Issue by AurelioSilver** [phob/pillarsofeternity-german-patch#150]
In vielen Fällen ist foreigner(s) als Ausländer übersetzt worden. Passt da nicht eher Fremder oder Fremde?

**Comment by MadOwlkin** [comment]
Bin dafür Fremde/r zu benutzen - ich finde Ausländer klingt sehr stark nach "Nationalstaaten und Reisepässen" anstatt nach dem doch im Dyrwald eher anzutreffenden "Ortschaften/Grafschaften und keiner kommt weiter als bis maximal zum nächsten Dorf".
