### ISSUE TITLE
Beta 2.0

### ISSUE THREAD

**Issue by AurelioSilver** [phob/pillarsofeternity-german-patch#169]
Soll am Montag wohl erscheinen.

Mal schauen, wieviel da geändert wurde und was mit der Übersetzung von den neuen Texten ist...

Gab's schon Rückmeldung, ob sie unsere Änderungen übernehmen? Allerdings gibt's dann noch das Problem auf dem Mac.

**Comment by Xaratas** [comment]
Nein, leider nichts an PMs im Forum gekommen.

**Comment by Xaratas** [comment]
Die Beta von 2.0 ist jetzt verfügbar.

**Comment by AurelioSilver** [comment]
Bin dabei erstmal die englischen Änderungen zu verfolgen. Sind hauptsächlich Rechtschreibfehler. Allerdings haben sich wohl auch neue Fehler eingeschlichen. Teilweise haben sie " an Zeilenenden mit Textabschnitten entfernt, die wir extra hinzugefügt haben. :)

**Comment by nkemnitz** [comment]
Die entfernten Anführungszeichen am Zeilenende (im Englischen) sind wahrscheinlich keine Fehler.
Hab mit AndreaColombo im Forum diskutiert. Wenn der Sprecher nicht wechselt, werden dort nur die Anführungszeichen am Anfang der einzelnen Absätze gesetzt und am Ende ausgelassen (außer beim letzten Absatz).

http://english.stackexchange.com/questions/96608/why-does-the-multi-paragraph-quotation-rule-exist

**Comment by AurelioSilver** [comment]
Gab's dann nicht Probleme mit dem Highlighting? Und wie sieht's bald mit einer neuen Version aus? Dann könnten wir uns an 2.0 dran setzen. Ich schaue noch, was man so aus 2.0 in die alte 1.6 mit rübernehmen kann. Teilweise wurden einige deutsche Sätze noch geändert. Ob nun besser oder schlechter ist teilweise Geschmackssache.

**Comment by AurelioSilver** [comment]
So. Patch 2.0 Beta 2 ist.

**Comment by AurelioSilver** [comment]
2.0 soll nun live auf Steam sein.

**Comment by Xaratas** [comment]
So ist es, und damit gibts neue Tickets :)
