### ISSUE TITLE
Patch 1.04 Beta

### ISSUE THREAD

**Issue by phob** [phob/pillarsofeternity-german-patch#83]
https://forums.obsidian.net/blog/7/entry-180-patch-notes-104/

Patch 1.04 beta available on steam.
- Update
- Check integrity
- make a new branch of it with git checkout --orphan

**Comment by AurelioSilver** [comment]
Ok.. There will be changes to the texts judging by the release notes.. Should backup, english 1.03 texts and compare them with the beta branch, when available..

**Comment by phob** [comment]
Git is our backup

**Comment by AurelioSilver** [comment]
Beta 1.04 ist live auf steam.

http://forums.obsidian.net/topic/76851-104-patch-beta-live-on-steam/

**Comment by phob** [comment]
Habe erst heute Abend Zeit. Wenn vorher jemand ein git checkout --orphan (und weiß wie das geht)machen könnte, wäre das super.

**Comment by AurelioSilver** [comment]
So unterschiedliche, englische Dateien von 1.03 zu 1.04 Beta 2

game\gui.stringtable
game\interactables.stringtable
game\items.stringtable
game\maps.stringtable

conversations\04_defiance_bay_brackenbury\04_cv_leaving_vision.stringtable
conversations\10_od_nua\1013_si_crystal_door.stringtable

quests\10_od_nua\10_qst_master_below.stringtable

Neu, wir eventuell gar nicht übersetzt?
conversations\px1_companions\px1_companion_cv_devil_voice_set

Die Unterschiede halten sich in Grenzen. Ein paasr Stings sind hinzugekommen, hauptsächlich im Game Ordner. Ansonsten 1 oder 2 Änderungen in den anderen Dateien.

Bei den deutschen Dateien sind nur die genannten im game Ordner unterschiedlich. Die Dateien wurden durch leere IDs, die neu in hinzugekommen sind, ergänzt.

**Comment by MadOwlkin** [comment]
sind die nur im deutschen leer (sprich müssen wir da einfach nachübersetzen) oder sowohl englisch als auch deutsch leer und damit egal? (Sitze leider auf der GoG-Version, da ist mit selber gucken nix)

**Comment by AurelioSilver** [comment]
Nur die deutschen sind leer, weil vermutlich noch nicht übersetzt. Die IDs wurden aber schon hinzugefügt. Ich würde die nun ja hinzufügen, weil es für die 1.03 keinen Unterschied machen sollte, wenn da neue ID dabei sind.. allerdings möchte ich erst die aktuellen Pullrequests integriert haben.

**Comment by AurelioSilver** [comment]
Heute kam nochmal ein Beta Update, aber bisher ohne Patchnotes. Es wurden nur wieder ein paar Dateien im game Ordner geändert. Hatte vor, die Beta Änderungen mal einzupflegen, aber eventuell warten wir lieber noch was.

**Comment by MadOwlkin** [comment]
Die Übersetzungen fehlen immernoch?

**Comment by AurelioSilver** [comment]
Ja.

**Comment by MadOwlkin** [comment]
Dann klingt das nach "dann übersetzen wir das halt selbst" ;)

Wie hattest du vor die neuen IDs einzupflegen? Erstmal leer? Erstmal auf Englisch mit Markierung dran ("TODO: " oder sowas)? Strings im Forum posten und wenn wir alle übersetzt haben hinzufügen?

**Comment by AurelioSilver** [comment]
Die englischen einfach dazu. Man sieht ja im commit was hinzugekommen ist. Nur bei den Sätzen, die sich geändert haben würde ich eventuell ein Issue aufmachen. Die neuen Texte scheinen aber selber noch nicht 100% fertig zu sein. Bei einem Text steht TEMP dran.

**Comment by MadOwlkin** [comment]
Bei "man sieht im commit" ist halt das Problem, dass es später relativ schwer ist die dann wieder irgendwie automatisiert heraus zu suchen um sicher zu sein, dass auch wirklich alle übersetzt wurden. Ich würde es ungern sehen, wenn wir zu 1.04 aus Schusseligkeit einen englischen String drin vergessen haben. (Aber wenn du da den Überblick behälst, dann hau sie so rein ;) )

**Comment by AurelioSilver** [comment]
Es hält sich bisher in Grenzen. Das sind ca. 10 neue Einträge pro Datei. Zumindest im Game Verzeichnis. Ich schau mal, ob ich heute abend zu komme.

**Comment by nkemnitz** [comment]
Patch 1.04 gibts nun auch auf gog.
Übersetzungs-Versuch in #112

**Comment by phob** [comment]
Ich mache heute Abend mal einen 1.04er branch auf und lade eine neue Version im Nexus hoch.

**Comment by MadOwlkin** [comment]
Im Endeffekt ist die deutsche Übersetzung in #112 relativ weit durch. Gibt noch 1 String, der grade hinterfragt wird und ein paar Strings, die "wohl zu neuem Content, der nicht drin ist" gehören. Ich würde vorschlagen #112 zu mergen, wenn der soweit ist und das dann direkt auf Nexus hochzuladen, damit da dann nicht heute eine Version mit 1.03 und morgen dann mit 1.04 kommt (wenn ich dich richtig verstanden hatte)

Btw. schön dich wieder da zu haben :)

**Comment by phob** [comment]
Der 1.04er branch ist nur eine unkorrigierte Kopie der 1.04 Sprachdateien die im Git verweilt.
Die neue Version im Nexus wird für die neue Version sein, klar. Ich warte bis #112 gemerget wurde.
Danke für den Hinweis :)

**Comment by nkemnitz** [comment]
In der neuen Version sind mittlerweile so viele Sachen hinzugekommen, die könntest auch gleich 0.3.0 nennen @phob :P

**Comment by phob** [comment]
recht haste. gesagt, getan :)

**Comment by Xaratas** [comment]
Patch mit 1.0.4 Inhalt ist raus. Dann mach ich das mal zu.
