### ISSUE TITLE
Wrong FemaleTexts

### ISSUE THREAD

**Issue by nkemnitz** [phob/pillarsofeternity-german-patch#84]
In some occasions there is a `<FemaleText>` tag provided that I don't think belongs there, since its a description of other people, not the main character.

TODO: Figure out the correct gender of the described characters (or find a neutral version), adjust the `<DefaultText>` and change the `<FemaleText>` tags back to `<FemaleText />`

Files affected (maybe more):
- stronghold.stringtable (ID46 and following)
- characters.stringtable (search for 'Edelfrau')

**Comment by LordCrash88** [comment]
The files I've checked so far had the female tag set right. But thanks for the heads up, will keep an eye out in future iterations.

**Comment by MadOwlkin** [comment]
characters.stringtable "Edelfrau" is correct. I was the one introducing it and verified, that characters.stringtable uses the gender of the NPC for choosing the tag. So a male NPC of type noble uses "Edelmann", a female uses "Edelfrau".

Only in conversations `<FemaleText>` uses the main character as point of view! At least in characters.stringtable the person described is also the point of view.

**Comment by nkemnitz** [comment]
Didn't know that @MadOwlkin, thanks for verifying!

The stronghold.stringtable however seems to work differently:
http://www.xup.in/dl,73007554/Festung_-_Status.jpg/ (reported by [Kirschrose](https://forums.obsidian.net/topic/71899-translation-errors-missing-translations-german/page-32#entry1662410))

**Comment by nkemnitz** [comment]
Fixed in #111
